### ISSUE TITLE
How do I do it on a corpus of search engine queries

### ISSUE THREAD

**Issue by MaheshChandrra** [renatoviolin/next_word_prediction#2]
Hi renatoviolin,is it possible to perform similar recommendations of words for search queries if I have already have a large corpus of search queries.I expect it needs a how training may I how do I do it on these tokenizers?

Thanks in advance!!

**Comment by renatoviolin** [comment]
Hi, for fine tuning I recommend you check the hugginface docs. They have a detailed tutorial on how to fine tune any model in your own data.
